name: Publish
on:
  push:
    tags: 
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "*.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
